apiVersion: v1
kind: Service
metadata:
  name: exercise-agent-service
  namespace: default
  labels:
    app: exercise-agent
spec:
  type: ClusterIP
  selector:
    app: exercise-agent
  ports:
  - port: 80
    targetPort: 8004
    protocol: TCP
    name: http
